numeros = [2,36,95,85,65,2.3,6.9,5]
print(numeros)
numeros.pop()
numeros.pop()
print(numeros)
numeros.append(8)
numeros.append(56)
numeros.append(68)
print(numeros)
numeros.insert(6,66)
print(numeros)
numeros.pop(-3)
print(numeros)
print(len(numeros))
print(sum(numeros))
media = len(numeros) / sum(numeros)
print(media)
numeros.sort(numeros)
print(numeros)